### ISSUE TITLE
Kontena::Etcd::Test::TestServer#logs does not work with refresh

### ISSUE THREAD

**Issue by SpComb** [SpComb/kontena-etcd#3]
Trying to rspec with `expect(etcd_server.logs).to eq [...]` after a refresh operation fails with a timeout:

```
I, [2017-01-04T13:26:12.771708 #7660]  INFO -- Kontena::Etcd::Writer: set /kontena/test1: {"test":1}
D, [2017-01-04T13:26:12.776202 #7660] DEBUG -- Kontena::Etcd::Client: set /kontena/test1 {:ttl=>30, :value=>"{\"test\":1}"}: set /kontena/test1@1520: {"test":1}
D, [2017-01-04T13:26:12.782380 #7660] DEBUG -- Kontena::Etcd::Client: refresh /kontena/test1 {:refresh=>true, :ttl=>30, :prevExist=>true, :prevValue=>"{\"test\":1}"}: compareAndSwap /kontena/test1@1521: {"test":1}
D, [2017-01-04T13:26:12.784441 #7660] DEBUG -- Kontena::Etcd::Client: get /kontena {}: get /kontena/@1520: test1
D, [2017-01-04T13:26:12.786881 #7660] DEBUG -- Kontena::Etcd::Client: watch /kontena {:wait=>true, :recursive=>true, :waitIndex=>1520, :timeout=>1.0}: set /kontena/test1@1520: {"test":1}
F
```

```
Failures:

  1) Kontena::Etcd::Writer for etcd with one node set #refresh updates the node
     Failure/Error:
       return @connection.request(method: method, path: path, query: query,
         headers: headers,
         body: body,
         expects: expects,
       )
     
     Timeout::Error:
       execution expired
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/socket.rb:263:in `select'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/socket.rb:263:in `select_with_timeout'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/socket.rb:49:in `rescue in readline'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/socket.rb:45:in `readline'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/response.rb:128:in `parse'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/response_parser.rb:7:in `response_call'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:388:in `response'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:252:in `request'
     # ./vendor/bundle/ruby/2.3.0/gems/webmock-2.3.1/lib/webmock/http_lib_adapters/excon_adapter.rb:62:in `handle_request'
     # ./vendor/bundle/ruby/2.3.0/gems/webmock-2.3.1/lib/webmock/http_lib_adapters/excon_adapter.rb:40:in `block in add_excon_stub'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/mock.rb:30:in `request_call'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:16:in `request_call'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:16:in `request_call'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:16:in `request_call'
     # ./vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:249:in `request'
     # ./lib/kontena/etcd/client.rb:52:in `http_request'
     # ./lib/kontena/etcd/keys.rb:52:in `keys_request'
     # ./lib/kontena/etcd/keys.rb:137:in `watch'
     # ./lib/kontena/etcd/test/test_server.rb:44:in `get_logs'
     # ./lib/kontena/etcd/test/test_server.rb:122:in `logs'
     # ./spec/kontena/etcd/writer_spec.rb:109:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:61:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:60:in `block (2 levels) in <top (required)>'
```

This is because the `Kontena::Etcd::Test::TestServer` expects to get a watch event for the current `X-Etcd-Index`, but because this action was a refresh, etcd does not return it from `GET ...?wait=true`.

The test should touch the root directory to ensure that it gets the final watch even for the resulting etcd index.

**Comment by SpComb** [comment]
The same thing happens if there is any modification to etcd outside of the test prefix at the end of the test.
